require("custom.default")
require("custom.dashboard")
require("default.lazy")
require("default.options")
require("default.autocommands")
require("user.colorscheme")
require("default.keymaps")
--require("user.nvim-tree")